config/urls.py
from __future__ import absolute_import
from django.conf.urls import patterns, url
from config import views 

urlpatterns = patterns(
    '',
    url(r'^$',
        views.index,
        name='index'),
    url(r'^delete_Terrarium',
        views.delete_Terrarium,
        name='delete_Terrarium'),
    url(r'^add_Terrarium.html$',
        views.add_Terrarium,
        name='add_Terrarium'),
    url(r'^add_light.html$',
        views.add_light,
        name='add_light'),
    url(r'^add_heater.html$',
        views.add_heater,
        name='add_heater'),
    url(r'^add_fogger.html$',
        views.add_fogger,
        name='add_fogger'),
    url(r'^add_sprinkler.html$',
        views.add_sprinkler,
        name='add_sprinkler'),
    url(r'^add_fan.html$',
        views.add_fan,
        name='add_fan'),
    url(r'^add_sht21.html$',
        views.add_sht21,
        name='add_sht21'),
    url(r'^add_WeatherURL',
        views.add_WeatherURL,
        name='add_WeatherURL'),
    url(r'^add_Job.html$',
        views.add_Job,
        name='add_Job'),
    url(r'^delete_Job.html$',
        views.delete_job,
        name='delete_job'),
    url(r'^jobs',
        views.jobs,
        name='jobs'),
    url(r'^actors',
        views.actors,
        name='actors'),
    url(r'^sensors',
        views.sensors,
        name='sensors'),
    url(r'^maintenance',
        views.maintenance,
        name='maintenance'),
)

karnipi/urls.py
from django.conf.urls import patterns, include, url

handler500 = 'karnipi.main.views.server_error'

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', include('main.urls', namespace="main")),
    url(r'^main/', include('main.urls', namespace="main")),
    url(r'^maintenance/', include('maintenance.urls', namespace="maintenance")),
    url(r'^config/', include('config.urls', namespace="config")),
    url(r'^camera/', include('camera.urls', namespace="camera")),
    url(r'^terrarium/', include('terrarium.urls', namespace="terrarium")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls import patterns, url

from main import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
)

maintenance/urls.py
from django.conf.urls import patterns, url

from maintenance import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
)

config/models.py
from django.db import models
from terrarium.models import Terrarium


class Config(models.Model):
    weatherURL = models.TextField()
    terrarium = models.ForeignKey(Terrarium, null=True)
    maintenance = models.BooleanField(default=False)

maintenance/models.py
from django.db import models

# Create your models here.

config/views.py
from __future__ import absolute_import

from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django import utils

from config.helper import ConfigHelper
from config.models import Config
from config.forms import NewLightForm, NewHeaterForm, NewFoggerForm, NewSprinklerForm, NewFanForm, NewJobForm, DeleteJobForm, \
    NewTerrariumForm, NewSHT21Form
from terrarium.models import Terrarium, Light, Heater, Fogger, Sprinkler, Fan, I2CActor, I2CSensor, SHT21Sensor as SHT21
from main.models import KarniPiLog
from main.logger import KarniLogger
from main.helper import MainHelper


def index(request):
    ch = ConfigHelper()
    crons = ch.GetCronTabs()
    config = ch.GetConfig()

    if config is None:
        config = ch.CreateConfig()

    light = None
    heater = None
    fogger = None
    fan = None
    sprinkler = None
    sht21 = None
    status_overview = None
    maintenance = None
    disk_space = None

    disk_space = ch.disk_usage()
    usage = int(disk_space[0])
    free = int(disk_space[1])

    if config.maintenance:
            status_overview = MainHelper().get_status_overview()

    terrarium = config.terrarium

    if terrarium is not None:
        light = Light.objects.filter(terrarium=terrarium)
        heater = Heater.objects.filter(terrarium=terrarium)
        fogger = Fogger.objects.filter(terrarium=terrarium)
        sprinkler = Sprinkler.objects.filter(terrarium=terrarium)
        fan = Fan.objects.filter(terrarium=terrarium)
        sht21 = SHT21.objects.filter(terrarium=terrarium)

    template = loader.get_template('config/index.html')
    context = RequestContext(request, {
        'crons': crons,
        'config': config,
        'terrarium': terrarium,
        'light': light,
        'heater': heater,
        'fogger': fogger,
        'sprinkler': sprinkler,
        'fan': fan,
        'sht21': sht21,
        'status_overview': status_overview,
        'maintenance': config.maintenance,
        'disk_space_usage': usage,
	'disk_space_free': free,
        'current_site': 'config',
    })
    return HttpResponse(template.render(context))


def jobs(request):
    ch = ConfigHelper()
    crons = ch.GetCronTabs()
    template = loader.get_template('config/jobs.html')
    context = RequestContext(request, {
        'crons': crons,
    })
    return HttpResponse(template.render(context))


def actors(request):
    config = ConfigHelper().GetConfig()

    if config.terrarium is None:
        raise Exception("No terrarium is configured. Please define a terrarium in configuration first!")
    else:
        objects = config.terrarium.get_actors()
        template = loader.get_template('config/actors.html')
        context = RequestContext(request, {
            'actors': objects,
        })
        return HttpResponse(template.render(context))


def sensors(request):
    config = ConfigHelper().GetConfig()
    objects = config.terrarium.get_sensors()
    template = loader.get_template('config/sensors.html')
    context = RequestContext(request, {
        'sensors': objects,
    })
    return HttpResponse(template.render(context))


def maintenance(request):
    config = ConfigHelper().GetConfig()
    status_overview = None

    if config.maintenance:
            status_overview = MainHelper().get_status_overview()

    template = loader.get_template('config/maintenance.html')
    context = RequestContext(request, {
        'status_overview': status_overview,
    })
    return HttpResponse(template.render(context))


def delete_Terrarium(request):
    config = Config.objects.all().first()
    terrarium = config.terrarium

    config.terrarium = None
    config.save()

    heater = Heater.objects.filter(terrarium_id=terrarium.id)
    fogger = Fogger.objects.filter(terrarium_id=terrarium.id)
    heater.all().delete()
    fogger.all().delete()

    title = terrarium.title

    try:
        Terrarium.objects.get(id=terrarium.id).delete()
        log = KarniPiLog(type='INFO',
                         datetime=utils.timezone.now(),
                         message="Terrarium '{0}' wurde aus der Konfiguration "
                                 + "entfernt".format(title))
        log.save()
    except:
        log = KarniPiLog(type='INFO',
                         datetime=utils.timezone.now(),
                         message="Es ist ein Fehler beim Entfernen des "
                                 + "Terrarium '{0}' aufgetreten".format(title))
        log.save()

    config = ConfigHelper().GetConfig()

    url = reverse('config:index')
    return HttpResponseRedirect(url)


def delete_job(request):
    if request.method == 'GET':
        form = DeleteJobForm()
    else:
        form = DeleteJobForm(request.POST)

        url = None

        if form.is_valid():
            str_title = None
            job_title_id = form.cleaned_data['title']
            choices = form.fields['title'].choices

            for c in choices:
                if int(job_title_id) == int(c[0]):
                    str_title = str(c[1])
                    break

            ConfigHelper().DeleteCronJob(str_title)

            url = reverse('config:index')

        return HttpResponseRedirect(url)
    return render(request, 'config/delete_Job.html', {'form': form})


def add_sht21(request):
    if request.method == 'GET':
        form = NewSHT21Form()
    else:
        form = NewSHT21Form(request.POST)

        if form.is_valid():
            sht_title = form.cleaned_data['title']
            sht_bank = form.cleaned_data['bank']
            sht_address = form.cleaned_data['address']
            sht_terra = form.cleaned_data['terrarium']
            SHT21.objects.create(title=sht_title,
                                 bank=sht_bank,
                                 address=sht_address,
                                 terrarium=sht_terra)

            url = reverse('config:index')

        return HttpResponseRedirect(url)
    return render(request, 'config/add_sht21.html', {'form': form})


def add_heater(request):
    if request.method == 'GET':
        form = NewHeaterForm()
    else:
        form = NewHeaterForm(request.POST)

        url = None

        if form.is_valid():
            title = form.cleaned_data['title']
            chip_address = form.cleaned_data['chip_address']
            data_address = form.cleaned_data['data_address']
            value_address = form.cleaned_data['value_address']
            terrarium = form.cleaned_data['terrarium']
            Heater.objects.create(title=title,
                                  chip_address=chip_address,
                                  data_address=data_address,
                                  value_address=value_address,
                                  terrarium=terrarium)

            url = reverse('config:index')

        return HttpResponseRedirect(url)
    return render(request, 'config/add_heater.html', {'form': form})


def add_light(request):
    if request.method == 'GET':
        form = NewLightForm()
    else:
        form = NewLightForm(request.POST)

        url = None

        if form.is_valid():
            title = form.cleaned_data['title']
            chip_address = form.cleaned_data['chip_address']
            data_address = form.cleaned_data['data_address']
            value_address = form.cleaned_data['value_address']
            terrarium = form.cleaned_data['terrarium']
            Light.objects.create(title=title,
                                 chip_address=chip_address,
                                 data_address=data_address,
                                 value_address=value_address,
                                 terrarium=terrarium)

            url = reverse('config:index')

        return HttpResponseRedirect(url)
    return render(request, 'config/add_light.html', {'form': form})


def add_fogger(request):
    if request.method == 'GET':
        form = NewFoggerForm()
    else:
        form = NewFoggerForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            chip_address = form.cleaned_data['chip_address']
            data_address = form.cleaned_data['data_address']
            value_address = form.cleaned_data['value_address']
            terrarium = form.cleaned_data['terrarium']

            Fogger.objects.create(title=title,
                                  chip_address=chip_address,
                                  data_address=data_address,
                                  value_address=value_address,
                                  terrarium=terrarium)

            url = reverse('config:index')

        return HttpResponseRedirect(url)
    return render(request, 'config/add_fogger.html', {'form': form})


def add_sprinkler(request):
    if request.method == 'GET':
        form = NewSprinklerForm()
    else:
        form = NewSprinklerForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            chip_address = form.cleaned_data['chip_address']
            data_address = form.cleaned_data['data_address']
            value_address = form.cleaned_data['value_address']
            terrarium = form.cleaned_data['terrarium']

            Sprinkler.objects.create(title=title,
                                  chip_address=chip_address,
                                  data_address=data_address,
                                  value_address=value_address,
                                  terrarium=terrarium)

            url = reverse('config:index')

        return HttpResponseRedirect(url)
    return render(request, 'config/add_sprinkler.html', {'form': form})


def add_fan(request):
    if request.method == 'GET':
        form = NewFanForm()
    else:
        form = NewFanForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']

maintenance/views.py
import sys
from django.conf import settings
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.views.decorators.cache import never_cache
from config.helper import ConfigHelper
from main.helper import MainHelper
from terrarium.helper import TerrariumHelper


@never_cache
def index(request):

    status_overview = MainHelper().get_status_overview()
    config = ConfigHelper().GetConfig()

    file_object = open(settings.BASE_DIR + '/main/logging/karnipi.log', 'r')
    log = file_object.read()
    file_object.close()

    if request.method == "POST":
        mode = request.POST.get('maintenance_mode', '')

        if mode == "an":
            config.maintenance = True
        else:
            config.maintenance = False

        config.save()

        template = loader.get_template('maintenance/index.html')
        context = RequestContext(request, {
        'status_overview': status_overview,
        'current_site': 'maintenance',
        'log': log,
        'maintenance_mode': config.maintenance,
        })
        print context
        return HttpResponse(template.render(context))

    else:
        print "doing something"
        template = loader.get_template('maintenance/index.html')
        context = RequestContext(request, {
            'status_overview': status_overview,
            'current_site': 'maintenance',
            'log': log,
            'maintenance_mode': config.maintenance,
        })
        return HttpResponse(template.render(context))

config/templates/config/actors.html
{% extends "base.html" %}
{% block title %}KarniPi - Aktoren{% endblock %}
{% block heading %}KarniPi - Aktoren{% endblock %}
{% block topnav %}
{% endblock %}

{% block content %}

<table class="table table-striped">
  <tr>
  <th>Titel</th><th>Chipadresse</th><th>Datenadresse</th><th>Wertadresse</th>
  </tr>
  {% for actor in actors.all %}
  <tr>
	<td>{{actor.title}}</td>
	<td>{{actor.chip_address}}</td>
	<td>{{actor.data_address}}</td>
	<td>{{actor.value_address}}</td>
  </tr>
  {%endfor%}
</table>

<div class="form-group">
    <form>
        {% csrf_token %}
        <input class="btn btn-default navbar-btn" id="btnAddActor" type="submit" formmethod="get"
               formaction="{% url 'config:add_Job' %}" value="Aktor anlegen"/>
    </form>
</div>

{% endblock %}

config/templates/config/add_Job.html
{% extends "base.html" %}

{% block title %}KarniPi - Job hinzufügen{% endblock %}

{% block heading %}KarniPi - Job hinzufügen{% endblock %}

{% block topnav %}
{% endblock %}

{% block content %}
<form role="form" action='/config/add_Job.html' method='post'> {% csrf_token %}
	<table class="form-table-fullWidth">
		{% for field in form %}
		<tr>
			<td class="form-td-label">{{ field.label_tag }}</td>
		</tr>
		<tr>
			<td class="form-td-input">{{ field.0 }}</td>
		</tr>
		{% endfor %}
	</table>
	<input type='submit' class="btn btn-default" value='Hinzufügen' />
</form>


{% endblock %}

config/templates/config/add_Terrarium.html
{% extends "base.html" %}

{% block title %}KarniPi - Terrarium hinzufügen{% endblock %}

{% block heading %}KarniPi - Terrarium hinzufügen{% endblock %}

{% block topnav %}
{% endblock %}

{% block content %}
<form role="form" action='/config/add_Terrarium.html' method='post'> {% csrf_token %}
	<table class="form-table-fullWidth">
		{% for field in form %}
		<tr>
			<td class="form-td-label">{{ field.label_tag }}</td>
		</tr>
		<tr>
			<td class="form-td-input">{{ field }}</td>
		</tr>
		{% endfor %}
	</table>
	<input type='submit' class="btn btn-default" value='Hinzufügen' />
</form>

{% endblock %}

config/templates/config/add_fogger.html
{% extends "base.html" %}

{% block title %}KarniPi - Vernebler hinzufügen{% endblock %}

{% block heading %}KarniPi - Vernebler hinzufügen{% endblock %}

{% block topnav %}
{% endblock %}

{% block content %}
<form role="form" action='/config/add_fogger.html' method='post'> {% csrf_token %}
	<table class="form-table-fullWidth">
		{% for field in form %}
		<tr>
			<td class="form-td-label">{{ field.label_tag }}</td>
		</tr>
		<tr>
			<td class="form-td-input">{{ field }}</td>
		</tr>
		{% endfor %}
	</table>
	<input type='submit' class="btn btn-default" value='Hinzufügen' />
</form>


{% endblock %}

config/templates/config/add_heater.html
{% extends "base.html" %}

{% block title %}KarniPi - Heizkomponente hinzufügen{% endblock %}

{% block heading %}KarniPi - Heizkomponente hinzufügen{% endblock %}

{% block topnav %}
{% endblock %}

{% block content %}
<form role="form" action='/config/add_heater.html' method='post'> {% csrf_token %}
	<table class="form-table-fullWidth">
		{% for field in form %}
		<tr>
			<td class="form-td-label">{{ field.label_tag }}</td>
		</tr>
		<tr>
			<td class="form-td-input">{{ field }}</td>
		</tr>
		{% endfor %}
	</table>
	<input type='submit' class="btn btn-default" value='Hinzufügen' />
</form>


{% endblock %}

config/templates/config/add_light.html
{% extends "base.html" %}

{% block title %}KarniPi - Lichtkomponente hinzufügen{% endblock %}

{% block heading %}KarniPi - Lichtkomponente hinzufügen{% endblock %}

{% block topnav %}
{% endblock %}

{% block content %}
<form role="form" action='/config/add_light.html' method='post'> {% csrf_token %}
	<table class="form-table-fullWidth">
		{% for field in form %}
		<tr>
			<td class="form-td-label">{{ field.label_tag }}</td>
		</tr>
		<tr>
			<td class="form-td-input">{{ field }}</td>
		</tr>
		{% endfor %}
	</table>
	<input type='submit' class="btn btn-default" value='Hinzufügen' />
</form>


{% endblock %}

config/templates/config/add_sht21.html
{% extends "base.html" %}

{% block title %}KarniPi - SHT21-Sensor hinzufügen{% endblock %}

{% block heading %}KarniPi - SHT21-Sensor hinzufügen{% endblock %}

{% block topnav %}
{% endblock %}

{% block content %}
<form role="form" action='/config/add_sht21.html' method='post'> {% csrf_token %}
	<table class="form-table-fullWidth">
		{% for field in form %}
		<tr>
			<td class="form-td-label">{{ field.label_tag }}</td>
		</tr>
		<tr>
			<td class="form-td-input">{{ field.0 }}</td>
		</tr>
		{% endfor %}
	</table>
	<input type='submit' class="btn btn-default" value='Hinzufügen' />
</form>


{% endblock %}

config/templates/config/add_sprinkler.html
{% extends "base.html" %}

{% block title %}KarniPi - Beregner hinzufügen{% endblock %}

{% block heading %}KarniPi - Beregner hinzufügen{% endblock %}

{% block topnav %}
{% endblock %}

{% block content %}
<form role="form" action='/config/add_sprinkler.html' method='post'> {% csrf_token %}
	<table class="form-table-fullWidth">
		{% for field in form %}
		<tr>
			<td class="form-td-label">{{ field.label_tag }}</td>
		</tr>
		<tr>
			<td class="form-td-input">{{ field }}</td>
		</tr>
		{% endfor %}
	</table>
	<input type='submit' class="btn btn-default" value='Hinzufügen' />
</form>


{% endblock %}

config/templates/config/details_I2CDevice.html
{% extends "base.html" %}

{% block title %}KarniPi - Konfiguration{% endblock %}

{% block heading %}KarniPi - Konfiguration{% endblock %}

{% block topnav %}
{% endblock %}

{% block content %}
<div>
	<h1>{{i2cdevice.title}}</h1>
	<span>{{i2cdevice.type}}</span>
	<input type='submit' value='Submit' />
</div>
{% endblock %}

config/templates/config/details_Job.html
{% extends "base.html" %}

{% block title %}KarniPi - Konfiguration{% endblock %}

{% block heading %}KarniPi - Konfiguration{% endblock %}

{% block topnav %}
{% endblock %}

{% block content %}
<div>
	<h1>{{job.title}}</h1>
	<span>{{job.command}}</span>
	<input type='submit' value='Submit' />
</div>
{% endblock %}

config/templates/config/index.html
{% extends "base.html" %}

{% block title %}KarniPi - Konfiguration{% endblock %}

{% block heading %}Konfiguration{% endblock %}
{% block topnav %}
{% endblock %}

{% block content %}
<style ty="text/css">
    .fixed-panel
    {
        height: 100%;
        width: 100%;
    }
    .fixed-panel .panel-heading, .fixed-panel .panel-body
    {
        text-align:center;
    }
    .fixed-panel .panel-body span.glyphicon {
        font-size: 4em;
    }

</style>
<div class="col-md-12">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">Terrarium</div>
            <div class="panel-body">
                <ul class="list-group">
                    {% if terrarium %}
                    <li class="list-group-item">
                        <b>Titel:</b> {{ terrarium.title }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Minimal-Temperatur:</b> {{ terrarium.temperature_min }} °C
                    </li>
                    <li class="list-group-item">
                        <b>Maximal-Temperatur:</b> {{ terrarium.temperature_max }} °C
                    </li>
                    <li class="list-group-item">
                        <b>Sonnenaufgang:</b> {{ terrarium.sunrise }} Uhr
                    </li>
                    <li class="list-group-item">
                        <b>Sonnenuntergang:</b> {{ terrarium.sunset }} Uhr
                    </li>
                    {% else %}
                    <div class="alert alert-danger" role="alert">
                        Aktuell ist kein Terrarium hinterlegt...
                    </div>
                    {% endif %}
                </ul>
                <form>
                    {% csrf_token %}
                    {% if terrarium %}
                    <input class="btn btn-default navbar-btn" id="btnDeleteTerrarium" type="submit" formmethod="get" formaction="{% url 'config:delete_Terrarium' %}" value="Terrarium löschen" />
                    {% else %}
                    <input class="btn btn-default navbar-btn" id="btnAddTerrarium" type="submit" formmethod="get" formaction="{% url 'config:add_Terrarium' %}" value="Terrarium anlegen" />
                    {% endif %}
                </form>
            </div>
        </div>
	<div class="panel panel-default">
	    <div class="panel-heading">
	    System
	    </div>
	    <div class="panel-body">
		<div id="piechart"></div>
	    </div>
    	</div>
    </div>
    <div class="col-md-8">
        <div class="col-md-4">
            <a href="{% url 'config:jobs' %}" style="color:#333;">
                <div class="panel panel-default fixed-panel">
                    <div class="panel-heading">Jobs</div>
                    <div class="panel-body">
                        <span class="glyphicon glyphicon-briefcase"></span>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'config:actors' %}" style="color:#333;">
                <div class="panel panel-default fixed-panel">
                    <div class="panel-heading">Aktoren</div>
                    <div class="panel-body">
                        <span class="glyphicon glyphicon-tint"></span>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'config:sensors' %}" style="color:#333;">
                <div class="panel panel-default fixed-panel">
                    <div class="panel-heading">Sensoren</div>
                    <div class="panel-body">
                        <span class="glyphicon glyphicon-dashboard"></span>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'maintenance:index' %}" style="color:#333;">
                <div class="panel panel-default fixed-panel">
                    <div class="panel-heading">Wartungsmodus</div>
                    <div class="panel-body">
                        <span class="glyphicon glyphicon-wrench"></span>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Description', 'Size'],
          ['Used', {{disk_space_usage}} ],
          ['Free', {{disk_space_free}} ],
        ]);

        var options = {
          title: 'Speicherauslastung',
	  legend: {position: 'bottom'},
	  slices: {
            0: { color: 'gray' },
            1: { color: 'green' }
          }

        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
      }
</script>

{% endblock %}

config/templates/config/jobs.html

{% extends "base.html" %}

{% block title %}KarniPi - Jobs{% endblock %}

{% block heading %}KarniPi - Jobs{% endblock %}

{% block topnav %}
{% endblock %}

{% block content %}
{% if crons %}
<table class="table table-striped">
    <thead>
        <th>Bezeichnung</th>
        <th>Minuten</th>
        <th>Stunden</th>
        <th>Tage</th>
        <th>Montate</th>
    </thead>
    <tbody>
        {% for cron in crons %}
        <tr>
            <td>
                {% if cron.enabled %}
                <input type="checkbox" checked="checked">
                {% else %}
                <input type="checkbox">
                {% endif %}
            </td>
            <td>{{cron.comment}}</td>
            <td>{{cron.minute}}</td>
            <td>{{cron.hour}}</td>
            <td>{{cron.day}}</td>
            <td>{{cron.month}}</td>
        </tr>
        {%endfor%}
    </tbody>
</table>
{%endif%}
<form>
        {% csrf_token %}
        <input class="btn btn-default navbar-btn" id="btnAddJob" type="submit" formmethod="get" formaction="{% url 'config:add_Job' %}" value="Job anlegen" />
        <input class="btn btn-default navbar-btn" id="btnDeleteJob" type="submit" formmethod="get" formaction="{% url 'config:delete_job' %}" value="Job löschen" />
    </form>
{% endblock %}

config/templates/config/maintenance.html
{% extends "base.html" %}
{% block title %}KarniPi - Wartungsmodus{% endblock %}
{% block heading %}KarniPi - Wartungsmodus{% endblock %}
{% block topnav %}
{% endblock %}

{% block content %}

<div class="panel panel-default">
	 	<div class="panel-heading">Status-Übersicht</div>
		<div class="panel-body">
            <table class="table">
                <tr>
                    <td>Licht</td>
                    <td>
                        {% if status_overview.light %}
                        <button type="button" class="btn btn-success pull-right">
                            <span class="glyphicon glyphicon-off"></span>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-default pull-right">
                            <span class="glyphicon glyphicon-off"></span>
                        </button>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>Heizung</td>
                    <td>
                        {% if status_overview.heater %}
                        <button type="button" class="btn btn-success pull-right">
                            <span class="glyphicon glyphicon-off"></span>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-default pull-right">
                            <span class="glyphicon glyphicon-off"></span>
                        </button>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>Vernebler</td>
                    <td>
                        {% if status_overview.fogger %}
                        <button type="button" class="btn btn-success pull-right">
                            <span class="glyphicon glyphicon-off"></span>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-default pull-right">
                            <span class="glyphicon glyphicon-off"></span>
                        </button>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>Beregnung</td>
                    <td>
                        {% if status_overview.sprinkler %}
                        <button type="button" class="btn btn-success pull-right">
                            <span class="glyphicon glyphicon-off"></span>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-default pull-right">
                            <span class="glyphicon glyphicon-off"></span>
                        </button>
                        {% endif %}
                    </td>
                </tr>
            </table>
	  	</div>
	</div>

<div class="form-group">
    <form>
        {% csrf_token %}
        <input class="btn btn-default navbar-btn" id="btnAddSensor" type="submit" formmethod="get" formaction="{% url 'config:index' %}" value="Sensor anlegen" />
    </form>
</div>

{% endblock %}

config/templates/config/sensors.html
{% extends "base.html" %}
{% block title %}KarniPi - Sensoren{% endblock %}
{% block heading %}KarniPi - Sensoren{% endblock %}
{% block topnav %}
{% endblock %}

{% block content %}

<table class="table table-striped">
  <tr>
  <th>Titel</th><th>Bank</th><th>Wertadresse</th>
  </tr>
  {% for sensor in sensors.all %}
  <tr>
	<td>{{sensor.title}}</td>
	<td>{{sensor.bank}}</td>
	<td>{{sensor.address}}</td>
  </tr>
  {%endfor%}
</table>

<div class="form-group">
    <form>
        {% csrf_token %}
        <input class="btn btn-default navbar-btn" id="btnAddSensor" type="submit" formmethod="get" formaction="{% url 'config:index' %}" value="Sensor anlegen" />
    </form>
</div>

{% endblock %}