config/urls.py
from __future__ import absolute_import
from django.conf.urls import patterns, url
from config import views 

urlpatterns = patterns(
    '',
    url(r'^$',
        views.index,
        name='index'),
    url(r'^delete_Terrarium',
        views.delete_Terrarium,
        name='delete_Terrarium'),
    url(r'^add_Terrarium.html$',
        views.add_Terrarium,
        name='add_Terrarium'),
    url(r'^add_light.html$',
        views.add_light,
        name='add_light'),
    url(r'^add_heater.html$',
        views.add_heater,
        name='add_heater'),
    url(r'^add_fogger.html$',
        views.add_fogger,
        name='add_fogger'),
    url(r'^add_sprinkler.html$',
        views.add_sprinkler,
        name='add_sprinkler'),
    url(r'^add_fan.html$',
        views.add_fan,
        name='add_fan'),
    url(r'^add_sht21.html$',
        views.add_sht21,
        name='add_sht21'),
    url(r'^add_WeatherURL',
        views.add_WeatherURL,
        name='add_WeatherURL'),
    url(r'^add_Job.html$',
        views.add_Job,
        name='add_Job'),
    url(r'^delete_Job.html$',
        views.delete_job,
        name='delete_job'),
    url(r'^jobs',
        views.jobs,
        name='jobs'),
    url(r'^actors',
        views.actors,
        name='actors'),
    url(r'^sensors',
        views.sensors,
        name='sensors'),
    url(r'^maintenance',
        views.maintenance,
        name='maintenance'),
)

karnipi/local/urls.py
/var/www/karnipi/karnipi/urls.py

karnipi/urls.py
from django.conf.urls import patterns, include, url

handler500 = 'karnipi.main.views.server_error'

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', include('main.urls', namespace="main")),
    url(r'^main/', include('main.urls', namespace="main")),
    url(r'^maintenance/', include('maintenance.urls', namespace="maintenance")),
    url(r'^config/', include('config.urls', namespace="config")),
    url(r'^camera/', include('camera.urls', namespace="camera")),
    url(r'^terrarium/', include('terrarium.urls', namespace="terrarium")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls import patterns, url

from main import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
)

templates/base (copy).html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>

	{% load staticfiles %}
	<!--<link rel="stylesheet" href="{% static '/static/weather/style.css' %}" />-->
	<link rel="stylesheet" href="{% static "weather/bootstrap.min.css" %}" />
	
	<!--<script type='text/javascript' src="{% static '/static/weather/style.js' %}"></script>-->
	
<!--	
	<link rel="stylesheet" href="{% static '/static/weather/jquery.fancybox.css' %}" type="text/css" media="screen" />
	<script type="text/javascript" src="{% static '/static/weather/jquery.fancybox.pack.js'%}"></script>
-->	
    	<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

<header id="top" class="navbar navbar-static-top bs-docs-nav" role="banner">	
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="../" class="navbar-brand">Bootstrap</a>
    </div>
    <nav id="bs-navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <a href="../getting-started/">Getting started</a>
        </li>
        <li>
          <a href="../css/">CSS</a>
        </li>
        <li>
          <a href="../components/">Components</a>
        </li>
        <li>
          <a href="../javascript/">JavaScript</a>
        </li>
        <li class="active">
          <a href="../customize/">Customize</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="http://themes.getbootstrap.com" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Themes');">Themes</a></li>
        <li><a href="http://expo.getbootstrap.com" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Expo');">Expo</a></li>
        <li><a href="http://blog.getbootstrap.com" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Blog');">Blog</a></li>
      </ul>
    </nav>
  </div>
</header>
<div id="content">

<!-- CONTAINER -->
<div class="container">

	<!-- HEADLINE -->
	<div class="row">
        <div class="col-md-2">
            <img src="{% static '/static/weather/img/karnipi_logo.png' %}" />
        </div>
        <div class="col-md-8">
            <h1>{% block heading %}{% endblock %}</h1>
        </div>
        <div class="col-md-2">
            {% if user.is_authenticated %}
            <h3>Hello {{ user.username }}!</h3>
            <a href="/main/logout/">Logout</a>
            {% else %}
            <h3><a href="/main/login/">Login</a></h3>
            {% endif %}
        </div>

    </div>
	<!-- HEADLINE -->
	<!-- TOPNAV 

	
  



	<div class="row">
		<form>
			<div class="btn-group btn-group-justified karnipi-mainnav">
		   		<div class="btn-group">
					{% if current_site == 'overview' %}
					<button id="btnMain" class="btn btn-active" type="submit" formaction="{% url 'main:index' %}">
						<span class="glyphicon glyphicon-list-alt"></span> <b>ÜBERSICHT</b>
					</button>
					{% else %}
					<button id="btnMain" class="btn btn-inactive" type="submit" formaction="{% url 'main:index' %}">
						<span class="glyphicon glyphicon-list-alt"></span> <b>ÜBERSICHT</b>
					</button>
					{% endif %}
				</div>
				<div class="btn-group">
					{% if current_site == 'terrarium_data' %}
					<button id="btnTerrariumLog" class="btn btn-active" type="submit" formaction="{% url 'terrarium:index' %}">
						<span class="glyphicon glyphicon-inbox"></span> <b>TERRARIUMDATEN</b>
					</button>
					{% else %}
					<button id="btnTerrariumLog" class="btn btn-inactive" type="submit" formaction="{% url 'terrarium:index' %}">
						<span class="glyphicon glyphicon-inbox"></span> <b>TERRARIUMDATEN</b>
					</button>
					{% endif %}
				</div>
                {% if user.is_authenticated %}
				<div class="btn-group">
					{% if current_site == 'camera' %}
					<button id="btnCamera" class="btn btn-active" type="submit" formaction="{% url 'camera:index' %}">
						<span class="glyphicon glyphicon-camera"></span> <b>KAMERA</b>
					</button>
					{% else %}
					<button id="btnCamera" class="btn btn-inactive" type="submit" formaction="{% url 'camera:index' %}">
						<span class="glyphicon glyphicon-camera"></span> <b>KAMERA</b>
					</button>
					{% endif %}
				</div>
				<div class="btn-group">
					{% if current_site == 'config' %}
					<button id="btnConfiguration" class="btn btn-active" type="submit" formaction="{% url 'config:index' %}">
						<span class="glyphicon glyphicon-cog"></span> <b>KONFIGURATION</b>
					</button>
					{% else %}
					<button id="btnConfiguration" class="btn btn-inactive" type="submit" formaction="{% url 'config:index' %}">
						<span class="glyphicon glyphicon-cog"></span> <b>KONFIGURATION</b>
					</button>
					{% endif %}
				</div>
                {% endif %}
			</div>
		</form>
	</div>
	TOPNAV -->
	<div class="row">
		
		<!-- CONTENT -->
		<div class="col-md-12">
		{% block content %}{% endblock %}
		</div>
		<!-- CONTENT -->
	</div>
</div>
<!-- CONTAINER -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script type='text/javascript' src="{% static "weather/bootstrap.min.js" %}"></script>
</div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static '/static/weather/style.css' %}" />
	<script type='text/javascript' src="{% static '/static/weather/jquery.js' %}"></script>
	<script type='text/javascript' src="{% static '/static/weather/style.js' %}"></script>
		
	<link rel="stylesheet" href="{% static '/static/weather/jquery.fancybox.css' %}" type="text/css" media="screen" />
	<script type="text/javascript" src="{% static '/static/weather/jquery.fancybox.pack.js'%}"></script>
	
    	<meta name="viewport" content="width=device-width, initial-scale=1">

	<style type="text/css">
		.karnipi-mainnav div button {
			font-size: 2em;
			background: none;
			border:0px solid white;
		}

		.karnipi-mainnav div button:hover
		{
			color:#71B238;
		}
	</style>
</head>
<body>

<!-- CONTAINER -->
<div class="container">

	<!-- HEADLINE -->
	<div class="row">
        <div class="col-md-2">
            <img src="{% static '/static/weather/img/karnipi_logo.png' %}" />
        </div>
        <div class="col-md-8">
            <h1>{% block heading %}{% endblock %}</h1>

        </div>
        <div class="col-md-2">
            {% if user.is_authenticated %}
            <h3>Hello {{ user.username }}!</h3>
            <a href="/main/logout/">Logout</a>
            {% else %}
            <h3><a href="/main/login/">Login</a></h3>
            {% endif %}
        </div>

    </div>
	<!-- HEADLINE -->
	<!-- TOPNAV -->
	<div class="row">
		<form>
			<div class="btn-group btn-group-justified karnipi-mainnav">
		   		<div class="btn-group">
					<button type="submit" formaction="{% url 'main:index' %}">
						HOME
					</button>
					<button type="submit" formaction="{% url 'terrarium:index' %}">
						MESSDATEN
					</button>
					<button type="submit" formaction="{% url 'camera:index' %}">
						KAMERA
					</button>
					<button type="submit" formaction="{% url 'config:jobs' %}">
						JOBS
					</button>
					<button type="submit" formaction="{% url 'config:actors' %}">
						AKTOREN
					</button>
					<button type="submit" formaction="{% url 'config:sensors' %}">
						SENSOREN
					</button>
					<button type="submit" formaction="{% url 'maintenance:index' %}">
						WARTUNG
					</button>
				</div>
			</div>
		</form>
	</div>
	<!-- TOPNAV -->
	<div class="row">
		
		<!-- CONTENT -->
		<div class="col-md-12">
		{% block content %}{% endblock %}
		</div>
		<!-- CONTENT -->
	</div>
</div>
<!-- CONTAINER -->
</body>
</html>